[package]
name = "futures"
version = "0.1.7"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["futures", "async", "future"]
repository = "https://github.com/alexcrichton/futures-rs"
homepage = "https://github.com/alexcrichton/futures-rs"
documentation = "https://docs.rs/futures"
description = """
An implementation of futures and streams featuring zero allocations,
composability, and iterator-like interfaces.
"""

[dependencies]
log = { version = "0.3", default-features = false }

[features]
use_std = []
with-deprecated = []
never_type = []
default = ["use_std", "with-deprecated"]

[workspace]
members = ["futures-cpupool"]
